[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  "yarn medusa db:migrate",
  "yarn medusa build"
]

[start]
cmd = "yarn start"